version: '3' 
services:
 pomodoro-db:
  image: postgres
  environment:
    - POSTGRES_DB=pomodorodb
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=Someya1024
    - POSTGRES_HOST_AUTH_METHOD=trust
  networks:
    - pomodoronet
  volumes:
    - pomodoro_db_volume:/var/lib/postgresql/data
  restart: always
  
 pomodoro-web: 
   build: . 
   command: uwsgi --socket :8001 --module app.wsgi --py-autoreload 1 --logto /tmp/mylog.log
   volumes:
     - .:/code
     - ./static:/static
   expose:
     - "8001"
   depends_on:
     - pomodoro-db
   networks:
     - pomodoronet

 nginx:
   image: nginx:1.13
   ports:
    - "8000:8000"
   volumes:
    - ./nginx/conf:/etc/nginx/conf.d
    - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
    - ./static:/static
    depends_on:
      -pomodoro-web
      
networks:
 pomodoronet:

volumes:
 pomodoro_db_volume: