version: '3' 
services:

 nginx:
  image: nginx:1.19.2
  ports:
   - "8000:8000"
  volumes:
   - type: bind
     source: "./nginx/conf"
     target: "/etc/nginx/conf.d"
   - type: bind
     source: "./nginx/uwsgi_params"
     target: "/etc/nginx/uwsgi_params"
   - type: bind
     source: "./static"
     target: "/static"
  depends_on:
   - pomodoro-web
  networks:
   - pomodoronet

 pomodoro-db:
  image: postgres
  environment:
    - POSTGRES_DB=pomodorodb
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=Someya1024
    - POSTGRES_HOST_AUTH_METHOD=trust
  networks:
    - pomodoronet
  volumes:
    - pomodoro_db_volume:/var/lib/postgresql/data
  restart: always
  
 pomodoro-web: 
   build: . 
   command: uwsgi --socket :8001 --module pomodoro.wsgi --py-autoreload 1 --logto /tmp/mylog.log
   volumes:
     - .:/code
     - ./static:/static
   expose:
     - "8001"
   networks:
     - pomodoronet
   depends_on:
     - pomodoro-db

      
networks:
 pomodoronet:

volumes:
 pomodoro_db_volume: