# Generated by Django 3.1 on 2021-02-09 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shuutyuudo', models.CharField(blank=True, max_length=2, verbose_name='集中度')),
                ('start_at', models.DateTimeField(auto_now_add=True, verbose_name='スタート日時')),
                ('end_at', models.DateTimeField(auto_now=True, verbose_name='終了日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name_plural': 'Focus',
            },
        ),
    ]
