# Generated by Django 3.1 on 2021-02-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoroapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focus',
            name='shuutyuudo',
            field=models.CharField(choices=[('1', 'クール'), ('0', 'キュート'), ('2', 'パッション')], max_length=2, verbose_name='集中度'),
        ),
    ]
