# Generated by Django 3.1 on 2021-02-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoroapp', '0002_auto_20210209_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focus',
            name='shuutyuudo',
            field=models.CharField(choices=[('2', 'パッション'), ('0', 'キュート'), ('1', 'クール')], max_length=2, verbose_name='集中度'),
        ),
    ]
