# Generated by Django 3.1 on 2021-02-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoroapp', '0003_auto_20210209_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focus',
            name='shuutyuudo',
            field=models.CharField(choices=[('0', 'キュート'), ('1', 'クール'), ('2', 'パッション')], max_length=2, verbose_name='集中度'),
        ),
    ]
