# Generated by Django 3.1 on 2021-02-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pomodoroapp', '0004_auto_20210209_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focus',
            name='shuutyuudo',
            field=models.CharField(choices=[('2', '2'), ('7', '7'), ('3', '3'), ('8', '8'), ('9', '9'), ('1', '1'), ('4', '4'), ('5', '5'), ('6', '6'), ('10', '10')], default=None, max_length=10, verbose_name='集中度'),
        ),
    ]
